# Generated by Django 2.1.dev20180227005752 on 2018-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20180303_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='persona',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(blank=True, null=True, to='mascota.Vacunas'),
        ),
    ]
