# Generated by Django 2.1.dev20180227005752 on 2018-03-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_auto_20180303_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacunas',
            new_name='Vacuna',
        ),
    ]
